apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: abidiqbal/backend:latest
        name: backend
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_NAME
          value: "demodb"
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_ENDPOINT
          value: "database"
        resources: {}
status: {}
