apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: database-deployment
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node2
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        env:
         - name: POSTGRES_USER
           value: "postgres"
         - name: POSTGRES_PASSWORD
           value: "123"
         - name: POSTGRES_DB
           value: "demodb"
        
status: {}
