apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: database-deployment
  name: database-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database-deployment
  type: ClusterIP
status:
  loadBalancer: {}
