apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deployment
  name: frontend-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  selector:
    app: frontend-deployment
  type: NodePort
status:
  loadBalancer: {}
