apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: database-deployment
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "demodb"
        
status: {}
