apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.backend_deployment.deployment_name }}
  name: {{ .Values.backend_service.service_name }}
spec:
  ports:
  - port: {{ .Values.backend_service.port }}
    protocol: {{ .Values.backend_service.protocol }}
    targetPort: {{ .Values.backend_service.target_port }}
  selector:
    app: {{ .Values.backend_deployment.deployment_name }}
  type: {{ .Values.backend_service.service_type }}
status:
  loadBalancer: {}

