apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app:  {{ .Values.database_deployment.deployment_name }}
  name:  {{ .Values.database_service.service_name }}
spec:
  ports:
  - port:  {{ .Values.database_service.port }}
    protocol:  {{ .Values.database_service.protocol }}
    targetPort: {{ .Values.database_service.target_port }}
  selector:
    app:  {{ .Values.database_deployment.deployment_name }}
  type: {{ .Values.database_service.service_type }}
status:
  loadBalancer: {}

