apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: abidiqbal/backend:latest
        name: backend
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_ENDPOINT
          value: "database"
        - name: POSTGRES_PORT 
          value: "5432"
        - name: POSTGRES_USER 
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: POSTGRES_USER  
        - name: POSTGRES_NAME
          value: "demodb"    
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: POSTGRES_PASSWORD
        resources: {}
status: {}
